name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    fail-fast: false
    matrix:
      compiler:
        - 'clang'
        - 'gcc'
    steps:
    - uses: actions/checkout@v1
    - name: Install valgrind
      run: |
         sudo apt install -y valgrind
    - name: Build and test
      env:
         CMAKE_OPTIONS: -DCMARK_SHARED=OFF
         CC: ${{ matrix.compiler }}
      run: |
         make
         make test
         make leakcheck

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      env:
         CMAKE_OPTIONS: -DCMARK_SHARED=OFF
      run: |
         make
         make test

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build and test
      run: |
        chcp 65001
        nmake.exe /nologo /f Makefile.nmake test
      shell: cmd
